version: '3.5'

services:
  ### TRAEFIK ###
  traefik:
    image: traefik:latest
    container_name: traefik
    hostname: traefik-branch
    restart: unless-stopped
    depends_on:
      - "pihole"
    ports:
      - 80:80
      - 443:443
    networks:
      revproxy:
        ipv4_address: 10.0.1.2
    security_opt:
      - no-new-privileges:true
    environment:
      - ACME_DNS_API_BASE=https://auth.acme-dns.io
      - ACME_DNS_STORAGE_PATH=/acme/dns.json
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_EMAIL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/acme/:/acme/
      - /data/logs/:/traefik-logs/
      - /data/traefik/etc-hosts:/etc/hosts:ro
      - /data/traefik/etc-traefik/:/etc/traefik/

  ### PIHOLE ###
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole-branch
    restart: unless-stopped
    depends_on:
      - "dhcphelper"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - 61103:80
      - 62103:443
    networks:
      revproxy:
        ipv4_address: 10.0.1.3
    environment:
      TZ: 'Europe/Madrid'
      WEBPASSWORD: ''
    volumes:
      - /data/pihole/etc-pihole/:/etc/pihole/
      - /data/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
      - /data/pihole/secrets.json:/secrets.json:ro
    cap_add:
      - NET_ADMIN

  ### DHCP HELPER ###
  dhcphelper:
    image: homeall/dhcphelper:latest
    container_name: dhcp-helper
    hostname: dhcp-helper
    restart: unless-stopped
    network_mode: "host"
    environment:
      IP: 10.0.1.3
      TZ: 'Europe/Madrid'
    cap_add:
      - NET_ADMIN

networks:
  revproxy:
    name: revproxy
    external: true
