version: "3"

services:
  node-red:
    image: nodered/node-red:latest-minimal
    container_name: node-red
    hostname: node-red
    ports:
      - 61008:1880
      - 62008:443
      - 63018:63018
    networks:
      revproxy:
        ipv4_address: 10.0.0.8
    environment:
      NODE_ENV: 'production'
#    user: "node-red"
    volumes:
      - /data/common/resolv.conf:/etc/resolv.conf:ro
      - /data/node-red/:/data/
      - /data/acme/:/acme/
      - /data/logs/:/logs/
    restart: unless-stopped
    #privileged: true

networks:
  revproxy:
    name: revproxy
    external: true
