version: '3.5'

services:
  files:
    image: drakkan/sftpgo:v2.5-alpine-slim
    container_name: files
    hostname: files
    restart: unless-stopped
    ports:
#      - 8080:8080
      - 61014:8090
#      - 2022:2022
#      - 10080:10080
    networks:
      revproxy:
        ipv4_address: 10.0.0.14
    user: "root"
    environment:
#      - SFTPGO_WEBDAVD__BINDINGS__0__PORT=10080
      - SFTPGO_HTTPD__BINDINGS__0__PORT=8090
    volumes:
      - /data/common/resolv.conf:/etc/resolv.conf:ro
      - /data/files/:/var/lib/sftpgo/
      - /SecurePool/:/data/secure/
      - /UnsecurePool/commonshare/:/data/common/

networks:
  revproxy:
    name: revproxy
    external: true
