version: "3"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    hostname: portainer
    restart: unless-stopped
    ports:
      - 61107:8000
      - 62107:9443
    networks:
      revproxy:
        ipv4_address: 10.0.1.7
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/portainer/data:/data
    entrypoint: "/portainer"

networks:
  revproxy:
    name: revproxy
    external: true

