version: "3"

services:
  mineserver:
    image: gakiteri/mineserver:ojdk21
    container_name: mineserver-mods
    hostname: mineserver-mods
    restart: unless-stopped
    ports:
      - 25565:25565
      - 25576:25575
    networks:
      revproxy:
        ipv4_address: 10.0.0.13
    user: 1001:1000
    volumes:
      - /mnt/wdssd/minecraft-mods-bcg/:/server/

networks:
  revproxy:
    name: revproxy
    external: true
