FROM alpine:latest

RUN mkdir /server && \
    printf "eula=true" > /server/eula.txt

WORKDIR /server

RUN apk --no-cache update && \
    apk --no-cache add openjdk19-jre-headless && \
    rm -rf /var/cache/apk/*

CMD ["java", "-Xmx8G", "-Xms8G", "-jar", "server.jar", "nogui"]
