FROM alpine:latest

RUN mkdir /server && \
    printf "eula=true" > /server/eula.txt

WORKDIR /server

RUN apk --no-cache update && \
    apk --no-cache add openjdk21-jre-headless && \
    rm -rf /var/cache/apk/*

CMD ["java", "-Xmx10G", "-jar", "fabric-server-launch.jar", "nogui"]
