version: "3.5"

services:
  ### TORRENT ###
  torrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: torrent
    hostname: torrent
    restart: unless-stopped
    ports:
      - 61015:61015
      - 6881:6881/tcp
      - 6881:6881/udp
    networks:
      revproxy:
        ipv4_address: 10.0.0.15
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=61015
    volumes:
      - /data/common/resolv.conf:/etc/resolv.conf:ro
      - /data/arr/torrent/:/config/
      - /UnsecurePool/commonshare/Torrent/:/downloads/

  ### INDEXER ###
  indexer:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: indexer
    hostname: indexer
    restart: unless-stopped
    ports:
      - 61017:9696
    networks:
      revproxy:
        ipv4_address: 10.0.0.17
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /data/common/resolv.conf:/etc/resolv.conf:ro
      - /data/arr/indexer/:/config/

  ### INDEXER - PROXY ###
  indexer-proxy:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: indexer-proxy
    hostname: indexer-proxy
    restart: unless-stopped
    ports:
      - 61018:8191
    networks:
      revproxy:
        ipv4_address: 10.0.0.18
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Europe/Madrid
    volumes:
      - /data/common/resolv.conf:/etc/resolv.conf:ro

  ### PELIS ###
  pelis:
    image: lscr.io/linuxserver/radarr:latest
    container_name: pelis
    hostname: pelis
    restart: unless-stopped
    ports:
      - 61019:7878
    networks:
      revproxy:
        ipv4_address: 10.0.0.19
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /data/common/resolv.conf:/etc/resolv.conf:ro
      - /data/arr/pelis/:/config/
      - /UnsecurePool/commonshare/Pelis/:/movies/
      - /UnsecurePool/commonshare/Torrent/:/downloads/

  ### SERIES ###
  series:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: series
    hostname: series
    restart: unless-stopped
    ports:
      - 61020:8989
    networks:
      revproxy:
        ipv4_address: 10.0.0.20
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /data/common/resolv.conf:/etc/resolv.conf:ro
      - /data/arr/series/:/config/
      - /UnsecurePool/commonshare/Series/:/tv/
      - /UnsecurePool/commonshare/Torrent/:/downloads/

  ### MUSIC ###
  music:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: music
    hostname: music
    restart: unless-stopped
    ports:
      - 61021:8686
    networks:
      revproxy:
        ipv4_address: 10.0.0.21
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /data/common/resolv.conf:/etc/resolv.conf:ro
      - /data/arr/music/:/config/
      - /UnsecurePool/commonshare/Music/:/music/
      - /UnsecurePool/commonshare/Torrent/:/downloads/


networks:
  revproxy:
    name: revproxy
    external: true
